version: 2
updates:
- package-ecosystem: maven
  directory: "/."
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.junit:junit-bom
    versions:
    - 5.7.0
  - dependency-name: org.jetbrains.kotlin:kotlin-maven-plugin
    versions:
    - 1.4.21-2
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib
    versions:
    - 1.4.21-2
  - dependency-name: org.codehaus.gmavenplus:gmavenplus-plugin
    versions:
    - 1.12.0
  - dependency-name: org.assertj:assertj-core
    versions:
    - 3.18.1
